### ISSUE TITLE
REE take can take translate indicies to out of bound indicies

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#201]
The only reason I can think of is out of bounds access on the array but this shouldn't happen for now

```
thread 'main' panicked at /Users/robert/repos/vortex/vortex-array/src/array/primitive/compute/take.rs:28:21:
index out of bounds: the len is 50 but the index is 50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88c2f4f5f50ace5ddc7655ea311435104d3659bd/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/88c2f4f5f50ace5ddc7655ea311435104d3659bd/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/88c2f4f5f50ace5ddc7655ea311435104d3659bd/library/core/src/panicking.rs:268:5
   3: vortex::array::primitive::compute::take::<impl vortex::compute::take::TakeFn for &dyn vortex::array::primitive::compute::PrimitiveTrait<T>>::take
   4: <dyn vortex::array::Array as vortex::array::WithArrayCompute>::with_compute::{{closure}}
   5: <vortex::array::primitive::PrimitiveArray as vortex::array::Array>::with_compute_mut
   6: vortex::compute::take::take
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   8: alloc::vec::in_place_collect::from_iter_in_place
   9: core::iter::adapters::try_process

  10: vortex_fastlanes::bitpacking::compute::<impl vortex::compute::take::TakeFn for vortex_fastlanes::bitpacking::BitPackedArray>::take
  11: <dyn vortex::array::Array as vortex::array::WithArrayCompute>::with_compute::{{closure}}
  12: vortex::compute::take::take

  13: vortex_ree::compute::<impl vortex::compute::take::TakeFn for vortex_ree::ree::REEArray>::take
  14: <dyn vortex::array::Array as vortex::array::WithArrayCompute>::with_compute::{{closure}}
  15: vortex::compute::take::take
  16: vortex_datetime::compute::<impl vortex::compute::take::TakeFn for vortex_datetime::datetime::DateTimeArray>::take
  17: <dyn vortex::array::Array as vortex::array::WithArrayCompute>::with_compute::{{closure}}
  18: vortex::compute::take::take
  19: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter

  20: core::iter::adapters::try_process
  21: vortex::array::struct_::compute::<impl vortex::compute::take::TakeFn for vortex::array::struct_::StructArray>::take
  22: <dyn vortex::array::Array as vortex::array::WithArrayCompute>::with_compute::{{closure}}
  23: vortex::compute::take::take

  24: vortex::array::chunked::compute::take::<impl vortex::compute::take::TakeFn for vortex::array::chunked::ChunkedArray>::take
  25: <dyn vortex::array::Array as vortex::array::WithArrayCompute>::with_compute::{{closure}}
  26: vortex::compute::take::take
  27: bench_vortex::reader::take_vortex
  28: criterion::bencher::Bencher<M>::iter
  29: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  30: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
  31: random_access::main
```

**Comment by robert3005** [comment]
I can't reproduce this anymore. I will assume this was #193 and refile when we see it again
